### ISSUE TITLE
No module named 'dataset.deepmind'

### ISSUE THREAD

**Issue by crazysal** [hendrycks/math#2]
Hi, similar to previous : 

```
Traceback (most recent call last):
  File "eval_math_gpt.py", line 37, in <module>
    from dataset.deepmind import DeepMindMathDataset
ModuleNotFoundError: No module named 'dataset.deepmind'
```

On commenting out the same next error : 

```
Traceback (most recent call last):
  File "eval_math_gpt.py", line 360, in <module>
    parser.add_argument('--arch', default='gpt2', choices=transformers.GPT2_PRETRAINED_MODEL_ARCHIVE_LIST)
AttributeError: module 'transformers' has no attribute 'GPT2_PRETRAINED_MODEL_ARCHIVE_LIST'

```

**Comment by hendrycks** [comment]
We have updated the script again. Hopefully it's workable.

**Comment by crazysal** [comment]
still getting the second error. which version of the lib do you have ?

**Comment by erictang000** [comment]
Seems to work for transformers 4.3.2 on my end.
